sudo: required
services:
  - docker

before_install:
  - docker build -t niteshsin786/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true niteshsin786/docker_react npm run test

deploy:
  edge: true
  provider: elasticbeanstock
  region: "ap-south-1"
  app: "docker_react"
  env: DockerReact-env
  bucket_name: elasticbeanstalk-ap-south-1-817180944609
  bucket_path: docker_react
  on:
    brach: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secret: "$AWS_SECRET_KEY"